name: coverage
on: [push, pull_request]
permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5.0.0
        with:
          distribution: 'zulu'
          java-version: 11
          cache: maven
      - name: Run tests and collect coverage
        run: ./mvnw -P coverage clean verify
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}