name: pre-submits
on: [pull_request]
permissions:
  contents: read
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5.0.0
        with:
          distribution: 'zulu'
          java-version: 11
          cache: maven
      - run: ./mvnw clean test
