name: Unit tests
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up JDK 11
      - uses: actions/setup-java@v5.0.0
        with:
          distribution: 'zulu'
          java-version: 11
          cache: maven
      - name: Build with Maven Wrapper
        run: ./mvnw clean package

